spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB # taille max d'un fichier uploadé (50MB)

springdoc:
  default-produces-media-type: application/json # type de contenu par défaut retourné pour les réponses JSON (application/json)

server:
  servlet:
    context-path: /api/v1/ # chemin de base de l'API REST (URL de base)
